# Generated by Django 4.2.20 on 2025-05-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="email",
            field=models.EmailField(
                default="vaishnavikashyap1804@gmail.com", max_length=254
            ),
            preserve_default=False,
        ),
    ]
