# Generated by Django 4.2.20 on 2025-05-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_doctor_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor", name="email", field=models.EmailField(max_length=254),
        ),
    ]
