# Generated by Django 5.2.1 on 2025-05-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_assessment', '0002_alter_selfassessment_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfassessment',
            name='analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selfassessment',
            name='recommendations',
            field=models.JSONField(default=list),
        ),
    ]
